# site.yml
---
- hosts: lamp1
  sudo: yes
  roles:
    - bertvv.el7
    - www
    - mariadb
    - wordpress
    - collectd
  vars:
    mariadb_root_password: root
    wordpress_user: wp_user
    wordpress_database: wp_db
    wordpress_password: wordpress
    wordpress_home_url: "http://192.0.2.53/wordpress"
    wordpress_site_title: Test Site
    wordpress_admin_user: admin
    wordpress_admin_user_pass: admin
    wordpress_admin_email: toon.lamberigts@gmail.com
    remote_wordpress_dir: /usr/share/wordpress
    remote_deploy_user: vagrant
- hosts: database
  sudo: yes
  roles: 
    - bertvv.el7 
    - mariadb
    - collectd
  vars:
    mariadb_databases:
      - wp_db
    mariadb_root_password: root
    mariadb_users:
      - name: wp_user
        host: 192.0.2.53
        password: wordpress
        priv: "wp_db.*:ALL,GRANT"
    mariadb_bind_address: 192.0.2.50
 
- hosts: monitoring
  sudo: yes
  roles:
    - bertvv.el7
    - www
    - mariadb
    - collectd
    - graphite
   
  vars:
    mariadb_databases:
      - graph_db
    mariadb_root_password: root
    mariadb_users:
      - name: graph_user
        host: localhost
        password: graphite
        priv: "graph_db.*:ALL,GRANT"
        
- hosts: dns
  sudo: yes
  roles:
    - bertvv.el7
    - bind
    - collectd
  handlers:
    - name: restart bind
      service:
        name: named
        state: restarted
    

