#####################################
#                                   #
#               Wordpress           #
#                                   #
#####################################
# roles/wordpress/tasks/main.yml
---

########### Install WordPress

- name: Create WordPress directory
  action: file
  args:
    path: "{{ remote_wordpress_dir }}"
    mode: 0755
    state: directory

- name: Is WP-CLI downloaded?
  stat: path="/usr/local/bin/wp"
  register: wpcli_is_downloaded

- name: Download WP-CLI
  shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  when: wpcli_is_downloaded.stat.exists == False
 
- name: Make WP-CLI executable
  file:
    path: wp-cli.phar
    mode: u=rwx,g=rx,o=rx
  when: wpcli_is_downloaded.stat.exists == False
 
- name: Move WP-CLI to /usr/local/bin/wp
  shell: mv wp-cli.phar /usr/local/bin/wp
  when: wpcli_is_downloaded.stat.exists == False

- name: Is WordPress downloaded?
  stat: path="{{ remote_wordpress_dir }}/index.php"
  register: wordpress_is_downloaded

- name: Download WordPress
  shell: /usr/local/bin/wp core download
  args:
    chdir: "{{ remote_wordpress_dir }}"
  when: wordpress_is_downloaded.stat.exists == False
 
- name: Configure WordPress
  shell: /usr/local/bin/wp core config
           --path="{{ remote_wordpress_dir }}"
           --dbname="{{ wordpress_database }}"
           --dbuser="{{ wordpress_user }}"
           --dbpass="{{ wordpress_password }}"
  when: wordpress_is_downloaded.stat.exists == False
  remote_user: "{{ remote_deploy_user }}"
  
- name: Install WordPress tables
  sudo: yes
  shell: /usr/local/bin/wp core install
            --path="{{ remote_wordpress_dir }}"
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"

- name: Apache config file for Wordpress
  copy:
    src=wordpress.conf
    dest=/etc/httpd/conf.d/wordpress.conf
    owner=root
    group=root
    mode=0644
    setype=httpd_config_t
  notify: restart httpd
  tags: wordpress

- name: Get Salts
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wordpress_salt
  tags: wordpress

- name: Generate 1000 posts with Lorem Ipsum content
  shell: curl http://loripsum.net/api/5 | /usr/local/bin/wp post generate --post_content --count=1000
  args:
    chdir: "{{ remote_wordpress_dir }}"  
