#####################################
#                                   #
#               Install             #
#                                   #
#####################################
# roles/mariaDB/tasks/install.yml




- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: mariadb_packages
  tags: mariadb
  
