# roles/collectd/tasks/common.yml
# Tasks that are common to servers and clients
---

- name: Ensure the EPEL repository is available
  yum:
    pkg: epel-release
    state: installed
  tags: collectd

- name: Install packages for collectd
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: collectd_packages
  tags: collectd

- name: Ensure the collectd service is started
  service:
    name: "{{ collectd_service }}"
    state: started
    enabled: true
  tags: collectd

- name: Install main configuration file
  template:
    src: etc_collectd.conf.j2
    dest: "{{ collectd_config_file }}"
    validate: "collectd -t -C %s"
  notify: restart collectd
  tags: collectd

- name: Install network configuration file
  template:
    src: etc_collectd.d_network.conf.j2
    dest: "{{ collectd_include_dir }}/network.conf"
    validate: "collectd -t -C %s"
  notify: restart collectd
  tags: collectd
  
- name: Copy Graphite Config
  template:
    src: graphite.conf.j2
    dest: "{{ collectd_include_dir }}graphite.conf"
  notify: restart collectd
  tags: collectd

- name: Copy Apache Config
  template:
    src: apache.conf.j2
    dest: "{{ collectd_include_dir }}apache.conf"
  notify: restart collectd
  tags: collectd
  
- name: Configure SELinux to allow collectd TCP connections
  seboolean: name=collectd_tcp_network_connect state=yes persistent=yes
