#####################################
#                                   #
#               LAMP                #
#                                   #
#####################################
# roles/lamp/tasks/main.yml
---
########## Install apache2
- name: 1. install Apache
  yum: name=httpd state=present

- name: 3. start Apache
  service: name=httpd state=running enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: install php 
  yum: name=php state=present
  
- name: 6. Install Mod SSL
  yum: name=mod_ssl state=present  

- name: 7. Is there an existing key?
  stat: path="/etc/pki/tls/certs/server.key"
  register: key  
  
- name: 8. Is there an existing certificate? 
  stat: path="/etc/pki/tls/certs/server.crt"
  register: cert
  
- name: 8. Create key/cert if not existing
  command: 'openssl req -new -nodes -x509 -subj "/C=BE/O=ToonCorp" -days 365 -x509 -nodes -out /etc/pki/tls/certs/server.crt -keyout /etc/pki/tls/private/server.key'
  when: (key.stat.exists == False) or (cert.stat.exists == False)
  notify: restart httpd
  
- name: 9. Install main configuration file
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: 10. Install mod_ssl configuration file
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd  
  
########### Install MariaDB

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: mariadb_packages
  tags: mariadb
  
- name: Make sure the MySQL extension for PHP is installed
  yum: 
    pkg: php-mysql
    state: installed
  notify: restart httpd
  
- name: Ensure service is started
  service:
    name: mariadb
    state: started
    enabled: yes
  tags: mariadb

- name: Install config file for network settings
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: /etc/my.cnf.d/network.cnf
  notify: restart mariadb
  tags: mariadb


- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ lamp_root_password }}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mariadb

- name: Install ~/.my.cnf
  template:
    src: home_my.cnf.j2
    dest: ~/.my.cnf
    mode: '0600'
  tags: mariadb

- name: Update root password
  mysql_user:
    name: root
    host: "{{ ansible_hostname }}"
    password: "{{ lamp_root_password }}"
    state: present
  when: ansible_hostname != 'localhost'
  tags: mariadb

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  tags: mariadb

- name: Remove anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags: mariadb

- name: Create the databases
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: lamp_databases
  tags: mariadb

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: lamp_users
  tags: mariadb




########### Configure Firewall

- name: Configure firewall
  script: ../files/firewall.sh