#####################################
#                                   #
#            Certificate            #
#                                   #
#####################################
# roles/www/tasks/services.yml




- name: Checking for existing key
  stat: path="/etc/pki/tls/certs/server.key"
  register: key  
  
- name: Checking for existing certificate 
  stat: path="/etc/pki/tls/certs/server.crt"
  register: cert
  
- name: Creating key/cert if not existing
  command: 'openssl req -new -nodes -x509 -subj "/C=BE/O=G02Corp" -days 365 -x509 -nodes -out /etc/pki/tls/certs/server.crt -keyout /etc/pki/tls/private/server.key'
  when: (key.stat.exists == False) or (cert.stat.exists == False)
  notify: restart httpd