###### BIND Variables
# roles/bind/vars/main.yml
    bind_packages:
      - bind
      - bind-utils
    bind_service: named
    bind_zone_master_server_ip: 192.0.2.52
    bind_zone_name: 'ops3-g02.org'
    bind_zone_networks:
      - "192.0.2"
    bind_zone_name_servers:
      - 'dns'
    # List of IPv4 address of the network interface(s) to listen on. Set to "any"
    # to listen on all interfaces
    bind_listen_ipv4:
      - "any"

    # List of IPv6 address of the network interface(s) to listen on.
    bind_listen_ipv6:
      - "any"

    # List of hosts that are allowed to query this DNS server.
    bind_allow_query:
      - "any"

    # By default, do not allow recursion, which is suitable for an authoritative
    # name server. (set to "yes" for an caching DNS server).
    bind_recursion: "no"

    # SOA information
    bind_zone_hostmaster_email: "hostmaster"
    bind_zone_ttl: "1W"
    bind_zone_time_to_refresh: "1D"
    bind_zone_time_to_retry: "1H"
    bind_zone_time_to_expire: "1W"
    bind_zone_minimum_ttl: "1D"
    
    bind_zone_hosts:
      - name: database
        ip: 192.0.2.50


      - name: monitoring
        ip: 192.0.2.51

      - name: dns
        ip: 192.0.2.52

        
      - name: wp
        ip: 192.0.2.53
        
      - name: wp
        ip: 192.0.2.54
      
      - name: wp
        ip: 192.0.2.55  


