# site.yml
---
- hosts: linuxlamp
  sudo: yes
  roles:
    - bertvv.el7
    - lamp
    - wordpress
  vars:
    lamp_databases:
      - wp_db
    lamp_root_password: fogMeHud8
    lamp_users:
      - name: wp_user
        password: CorkIgWac
        priv: "wp_db.*:ALL,GRANT"
    wordpress_database: wp_db
    wordpress_user: wp_user
    wordpress_password: CorkIgWac
    wordpress_home_url: "http://192.0.3.50/wordpress"
    wordpress_site_title: Test Site
    wordpress_admin_user: admin
    wordpress_admin_user_pass: admin
    wordpress_admin_email: toon.lamberigts@gmail.com
    remote_wordpress_dir: /usr/share/wordpress
    remote_deploy_user: vagrant
    mariadb_packages:
      - mariadb
      - mariadb-server
      - MySQL-python

 

